### ISSUE TITLE
Prop validation doesn't work.

### ISSUE THREAD

**Issue by sect2k** [krakenjs/zoid#301]
Hey!

First of all, just want to say thanks and express my appreciation for your work on this library, it's excellent. 

Looks like `validate` method on prop definition never gets called and from looking at the source code, it seems that it's conditioned by `__DEBUG__` being true.

**Comment by mnicpt** [comment]
@sect2k Thank you for taking the time to bring up this issue! :)  We just merged a fix for this yesterday. This will be included in our next release.

**Comment by nehapatwardhan6490** [comment]
@mnicpt has this been release? I am still seeing this issue in version "9.0.54". validations in the prop is not getting called on creation.

**Comment by mnicpt** [comment]
@nehapatwardhan6490 Yes, this has been released. https://github.com/krakenjs/zoid/blob/f9099ca17102a90e24d9b13dcaf0ae9b7655db3f/src/component/props.js#L175 Can you open another ticket regarding your issue with the details as this issue was more about removing the `debug` conditional.
